name: API CI

on:
  push:
    paths:
      - "./api/**"
      - "./.github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/chechout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        whit:
          node-version: 16.13.x
          cache: npm
          cache-dependency-path: ./api/package-lock.json

      - name: Install dependencys
        shell: bash
        run: npm ci

      - name: Run unit test
        shell: bash
        run: npm run test
