name: API CI

# for normal repo
# on: [push]

# for monorepo
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api


#for all
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/chechout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        whit:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install dependencys
        shell: bash
        run: npm ci
      - name: Run unit test
        shell: bash
        run: npm run test


